spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}          # переменная окружения
    password: ${MAIL_PASSWORD}      # переменная окружения
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true

logging:
  level:
    com.alekseev.notificationservice: DEBUG
