spring:
  kafka:
    bootstrap-servers: kafka:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
  instance:
    preferIpAddress: true