spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: user_service_user
    password: StrongPassword_123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
  instance:
    preferIpAddress: true

resilience4j.circuitbreaker:
  instances:
    notificationService:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      failureRateThreshold: 50