spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_service_db
    username: user_service_user
    password: StrongPassword_123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1   # добавить эту строку

resilience4j.circuitbreaker:
  instances:
    notificationService:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
